home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name="index"),
]

subscribers/urls.py
from django.urls import path
from . import views

app_name = 'subscribers'
urlpatterns = [
    path('', views.index, name="index"),
    path('register/', views.register, name="register"),
    path('register/check_email', views.check_email, name="check_email"),
    path('register/submit', views.submit, name="submit"),
    path('list/', views.list, name="list"),
    path('unsubscribe/', views.unsubscribe, name="unsubscribe")
]

tedede/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('about/', include('about.urls')),
    path('books/', include('books.urls')),
    path('subscribers/', include('subscribers.urls')),
    path('social/', include('social_django.urls', namespace='social')),
    path('oauth/', include('oauth.urls'))
]

subscribers/models.py
from django.core.validators import MinLengthValidator
from django.db import models


class Subscriber(models.Model):
    name = models.CharField("nama", max_length=64)
    email = models.EmailField("alamat surel", max_length=128, unique=True)
    password = models.CharField(
        "kata sandi", max_length=32, validators=[MinLengthValidator(8)]
    )

    class Meta:
        verbose_name = 'pelanggan'
        verbose_name_plural = 'pelanggan-pelanggan'

    @classmethod
    def list(cls):
        return {
            'subscribers': [object.serialize() for object in cls.objects.all()]
        }

    def __str__(self):
        return f"{self.name} ({self.email})"

    def serialize(self):
        return {
            'id': self.id,
            'name': self.name,
            'email': self.email
        }

subscribers/forms.py
from django import forms
from subscribers.models import Subscriber


class SubscriberForm(forms.ModelForm):
    class Meta:
        model = Subscriber
        fields = '__all__'
        widgets = {
            'email': forms.EmailInput(
                attrs={'placeholder': 'alamat@surel.com'}
            ),
            'name': forms.TextInput(
                attrs={'placeholder': 'Nama Anda'}
            ),
            'password': forms.PasswordInput(
                attrs={'placeholder': 'Kata sandi, minimal 8 karakter'}
            )
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.label_suffix = ''

subscribers/views.py
from django.core.exceptions import ValidationError
from django.core.serializers import serialize
from django.core.validators import MaxLengthValidator, validate_email
from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_protect

from subscribers.forms import SubscriberForm
from subscribers.models import Subscriber

import json


def index(request):
    return render(request, 'subscribers/index.html')


def register(request):
    context = {}
    context['form'] = form = SubscriberForm(request.POST or None)
    return render(request, 'subscribers/register.html', context)


def submit(request):
    form = SubscriberForm(request.POST)
    if form.is_valid():
        form.save()
        return JsonResponse(
            {'success': True},
            json_dumps_params={'indent': 2}
        )
    response = JsonResponse(
        {'success': False, 'errors': form.errors},
        json_dumps_params={'indent': 2}
    )
    response.status_code = 403
    return response


def check_email(request):
    email = request.GET.get('email', '')
    response = {'valid' : None, 'exists': None, 'messages': []}
    validate_max_length = MaxLengthValidator(128)
    try:
        validate_max_length(email)
        validate_email(email)
    except ValidationError as error:
        response['valid'] = False
        response['messages'] = error.messages
    else:
        response['valid'] = True
        if Subscriber.objects.filter(email=email):
            response['exists'] = True
            response['messages'] = Subscriber.unique_error_message(
                Subscriber, Subscriber, ['email']
            ).messages
        else:
            response['exists'] = False
    response['messages'] = [
        message.capitalize() for message in response['messages']
    ]
    return JsonResponse(response)


def list(request):
    return JsonResponse(
        Subscriber.list(),
        json_dumps_params={'indent': 2}
    )


@csrf_protect
def unsubscribe(request):
    email = request.POST.get('email', '')
    password = request.POST.get('password', '')
    query = Subscriber.objects.filter(email=email, password=password)
    try:
        subscriber = query.get()
    except Subscriber.DoesNotExist as error:
        response = JsonResponse({'success': False, 'message': str(error)})
        response.status_code = 403
    else:
        subscriber.delete()
        response = JsonResponse(
            {'success': True, 'message': f'{email} has been unsubscribed.'}
        )
    return response

subscribers/templates/subscribers/base.html
{% extends 'tedede/base.html' %}

{% block navbar %}
{% with current_nav='subscribers' %}
{{ block.super }}
{% endwith %}
{% endblock navbar%}

subscribers/templates/subscribers/index.html
{% extends 'subscribers/base.html' %}
{% load static %}

{% block title %}{{ block.super }} - Pelanggan{% endblock title %}

{% block content %}
<div class="py-4"></div>
<div id="subscriber-results">
  <div id="subscriber-results-header" class="px-2 serif">
    <h1 class="sans-serif px-1 py-2 text-warning">Pelanggan</h1>
    <p id="results-exist" class="text-secondary pl-3 my-3">
      Daftar semua pelanggan situs ini.
    </p>
    <p id="results-empty" class="text-secondary pl-3 my-3" style="display: none;">
      Belum ada pelanggan di situs ini.
    </p>
  </div>

  <div id="subscriber-results-table" class="table-responsive my-5 px-4 py-2">
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th class="align-middle" scope="col">No.</th>
          <th class="align-middle" scope="col">Nama</th>
          <th class="align-middle" scope="col">Alamat surel</th>
          <th class="align-middle" scope="col">Langganan</th>
        </tr>
      </thead>
      <tbody id="tbody-results">
      </tbody>
    </table>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="unsub-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content text-dark">
      <div class="modal-header">
        <h5 class="modal-title" id="unsub-modal-label">Berhenti berlangganan</h5>
        <button type="button" class="close" data-dismiss="modal">
          <span>&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Masukkan kata sandi pelanggan ini (<span id="subscriber_email"></span>) untuk konfirmasi penghentian langganan.
        <form class="font-weight-medium px-5 py-3" method="post">
            {% csrf_token %}
            <input type="hidden" name="email" value="" id="id_email">
            <div class="py-2"></div>
            <div id="form_password" class="input-group mb-2">
                <input type="password" name="password" placeholder="Kata sandi, minimal 8 karakter" maxlength="32" class="form-control" required="" id="id_password">
            </div>
            <div id="form_password_toggle" class="form-check">
                <input id="password-toggle" class="form-check-input" type="checkbox" onchange="togglePassword()">
                <label class="form-check-label" for="password-toggle">Perlihatkan kata sandi</label>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary font-weight-medium" data-dismiss="modal">Batal</button>
              <button id="id_submit" type="submit" class="font-weight-medium btn btn-danger my-4">Hapus</button>
            </div>
        </form>
        <h5 id="fail-message" class="font-weight-medium text-danger" style="display: none;">Kata sandi salah.</h5>
      </div>
    </div>
  </div>
</div>

<div class="py-3"></div>
{% endblock content %}
{% block custom_scripts %}
<script src="{% static "subscribers/js/manage.js" %}"></script>
{% endblock custom_scripts %}

subscribers/templates/subscribers/register.html
{% extends 'subscribers/base.html' %}
{% load static %}

{% block navbar %}
{% with current_nav='subscribers' %}
{{ block.super }}
{% endwith %}
{% endblock navbar%}

{% block title %}{{ block.super }} - Berlangganan{% endblock title %}

{% block content %}
  <div class="py-5"></div>
  <div id="register-header" class="serif px-3">
    <h1 class="sans-serif py-2 text-warning">Berlangganan</h1>
    <p class="text-secondary">Jadilah pelanggan situs ini dan dapatkan pemberitahuan mengenai hal terbaru.</p>
  </div>
  <div class="py-3"></div>
  <form class="font-weight-medium px-5 py-3" method="post">
    {% csrf_token %}
    {% for field in form.visible_fields %}
      <label class="mt-3" for="{{ field.name }}">{{ field.label }}</label>
      <div id="form_{{ field.name }}" class="input-group mb-2">
        {{ field }}
      </div>
      {% if field.name == 'password' %}
      <div id="form_{{ field.name }}_toggle" class="form-check">
        <input id="password-toggle" class="form-check-input" type="checkbox" onchange="togglePassword()">
        <label class="form-check-label" for="password-toggle">Perlihatkan kata sandi</label>
      </div>
      {% endif %}
      {% for error in field.errors %}
        <div id="{{ field.name }}_errors" class="input-group">
          <p class="font-weight-medium text-danger">{{ error.capitalize|escape }}</p>
        </div>
      {% endfor %}
    {% endfor %}
    <button id="id_submit" type="submit" class="font-weight-medium btn btn-warning my-4" disabled>
      Daftar
    </button>
  </form>
  <h5 id="success-message" class="font-weight-medium text-success" style="display: none;">Data berhasil disimpan.</h5>
  <h5 id="fail-message" class="font-weight-medium text-danger" style="display: none;">Data tidak valid.</h5>
  <div class="py-3"></div>
{% endblock content %}

{% block custom_scripts %}
<script src="{% static "subscribers/js/register.js" %}"></script>
{% endblock custom_scripts %}