about/urls.py
from django.urls import path
from . import views

app_name = 'about'
urlpatterns = [
    path('', views.index, name="index"),
]

books/urls.py
from django.urls import path
from . import views

app_name = 'books'
urlpatterns = [
    path('', views.index, name="index"),
    path('volumes/', views.volumes, name="volumes"),
    path('volumes/<slug:book_id>', views.volumes, name="volumes_details"),
    path('my_books/', views.my_books, name="my_books"),
    path('favorite/', views.favorite, name="favorite"),
    path('unfavorite/', views.unfavorite, name="unfavorite"),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name="index"),
]

oauth/urls.py
from django.urls import path
from . import views

app_name = 'oauth'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('welcome/', views.welcome, name='welcome'),
    path('is_logged_in/', views.is_logged_in, name='is_logged_in')
]

subscribers/urls.py
from django.urls import path
from . import views

app_name = 'subscribers'
urlpatterns = [
    path('', views.index, name="index"),
    path('register/', views.register, name="register"),
    path('register/check_email', views.check_email, name="check_email"),
    path('register/submit', views.submit, name="submit"),
    path('list/', views.list, name="list"),
    path('unsubscribe/', views.unsubscribe, name="unsubscribe")
]

tedede/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('about/', include('about.urls')),
    path('books/', include('books.urls')),
    path('subscribers/', include('subscribers.urls')),
    path('social/', include('social_django.urls', namespace='social')),
    path('oauth/', include('oauth.urls'))
]

templates/components/navbar.html
<nav class="navbar {% if collapsed %}navbar-md{% else %}navbar-expand-md{% endif %} fixed-top bg-semidark navbar-dark">
  <a class="navbar-brand" href="{% url 'home:index' %}">sage</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse order-1 order-md-0 dual-collapse" id="collapsibleNavbar">
    {% block navbar_contents %}
    <ul class="navbar-nav mr-auto">
      <li class="nav-item mx-2">
        <a class="nav-link{% if current_nav == 'home' %} font-weight-medium text-light{% endif %}" href="{% url 'home:index' %}">Beranda</a>
      </li>
      <li class="nav-item mx-2">
        <a class="nav-link{% if current_nav == 'books' %} font-weight-medium text-light{% endif %}" href="{% url 'books:index' %}">Buku</a>
      </li>
      <li class="nav-item mx-2 dropdown">
        <a class="nav-link dropdown-toggle{% if current_nav == 'subscribers' %} font-weight-medium text-light{% endif %}" href="#" id="subscriber-dropdown" data-toggle="dropdown" role="button">
          Pelanggan
        </a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'subscribers:register' %}">Berlangganan</a>
          <a class="dropdown-item" href="{% url 'subscribers:index' %}">Daftar pelanggan</a>
        </div>
      </li>
      <li class="nav-item mx-2">
        <a class="nav-link{% if current_nav == 'about' %} font-weight-medium text-light{% endif %}" href="{% url 'about:index' %}">Tentang</a>
      </li>
      <li class="nav-item mx-2">
        <a class="nav-link" href="https://gitlab.com/laymonage/tedede">Repo GitLab</a>
      </li>
    </ul>
  </div>
  <div class="collapse navbar-collapse order-3 dual-collapse">
    <ul class="navbar-nav ml-auto">
      <div id="mode-button" class="nav-item btn-group-toggle mx-2 my-2 my-md-0" data-toggle="buttons">
        <label class="btn btn-secondary">
          <input id="mode-checkbox" type="checkbox">
          <span id="mode-text" class="font-weight-medium">terang</span>
        </label>
      </div>
      <div id="log-button" class="nav-item mx-2 my-2 my-md-0">
        <a class="btn btn-primary font-weight-medium"
          {% if user.is_authenticated %}
            href="{% url 'oauth:logout' %}">Keluar
          {% else %}
            href="{% url 'oauth:login' %}">Masuk
          {% endif %}
        </a>
      </div>
    </ul>
    {% endblock navbar_contents%}
  </div>
</nav>